### ISSUE TITLE
Replace /tree/ with /blob/ when specifying branch?

### ISSUE THREAD

**Issue by pdehaan** [zeke/github-url-to-object#13]
Currently this works:

```js
var gh = require('github-url-to-object')

console.log(gh('hapijs/hapi').https_url); // https://github.com/hapijs/hapi
console.log(gh('hapijs/hapi#lts').https_url); // https://github.com/hapijs/hapi/tree/lts
```

... but I think once you start appending filenames onto the strings, GitHub converts the /tree/ path to /blob/, which was giving me some issues in a script.

For example, https://github.com/hapijs/hapi/tree/lts/npm-shrinkwrap.json redirects to https://github.com/hapijs/hapi/blob/lts/npm-shrinkwrap.json

I either had to do a regex/string like:
```js
url = url.replace('/tree/', '/blob/');
```

Or I guess I could probably look at following redirects with **request** or **wreck** modules. But possibly better to return the final URL if possible instead of having the server do a redirect.

**Comment by zeke** [comment]
Good catch, @pdehaan. Would love a PR for this!
