### ISSUE TITLE
Latest bower build is empty

### ISSUE THREAD

**Issue by appleton** [zeke/github-url-to-object#17]
The contents of the gh.js file is empty in your 1.4.2 tag https://github.com/zeke/github-url-to-object/blob/1.4.2/dist/gh.js

**Comment by zeke** [comment]
Gah! Bower.

**Comment by zeke** [comment]
Do you need me to do something, or does https://github.com/zeke/github-url-to-object/releases/tag/v2.2.0 do the trick?

**Comment by appleton** [comment]
Probably bump the version in the bower.json? Honestly I could just switch to install this via npm...

**Comment by zeke** [comment]
>  install this via npm

Please do! Bower is silly.
