### ISSUE TITLE
Fails to parse www.github.com URLS

### ISSUE THREAD

**Issue by pdehaan** [zeke/github-url-to-object#21]
Randomly spotted a GitHub URL like http://www.github.com/sinnerschrader/aem-react-js

The awesome page at https://zeke.github.io/github-url-to-object/ says:

```json
{
  "error": "Invalid GitHub URL"
}
```

But it looks like it works as expected if I drop the "www." subdomain.

Also https://github.com/KlwntSingh/fs-advanced/blob/a053cc8930af8073687f3c715c254b5d553c2fb3/package.json#L28

**Comment by zeke** [comment]
Thanks for reporting, @pdehaan. This fix landed in 2.2.4

**Comment by pdehaan** [comment]
![](https://media.giphy.com/media/dkGhBWE3SyzXW/giphy.gif)
