### ISSUE TITLE
Parser fails if repo owner has a period in name

### ISSUE THREAD

**Issue by pdehaan** [zeke/github-url-to-object#23]
https://zeke.github.io/github-url-to-object/ fails to parse `git+https://github.com/alexisvincent.io/js-kernel.git`. If you remove the "." in ".io", it parses as expected.

You can also see this with fetch-nice-package using the following snippet:

```js
const fetchNicePackage = require('fetch-nice-package');

fetchNicePackage('js-kernel')
  .then(({name, version, repository}) => ({name, version, repository}))
  .then(pkg => JSON.stringify(pkg, null, 2))
  .then(output => console.log(output))
  .catch(err => console.error(err));

/* Output:
{
  "name": "js-kernel",
  "version": "0.0.9",
  "repository": null
}
*/
```

Gets slightly weirder, as apparently the correct repo is https://github.com/alexisvincent/js-kernel (versus /alexisvincent.io/).

**Comment by zeke** [comment]
Can GitHub usernames contain periods?

**Comment by pdehaan** [comment]
GitHub, apparently not. 

<img width="497" alt="join_github_ _github" src="https://cloud.githubusercontent.com/assets/557895/18235233/23991b46-72cd-11e6-9ed3-a88677b44914.png">

But on the brightside, I did fix the repo name in the package.json upstream, so there's that.

**Comment by zeke** [comment]
> what.the.actual

Haha.
