### ISSUE TITLE
Not supported: git://github.com/feross/standard.git

### ISSUE THREAD

**Issue by bfred-it** [zeke/github-url-to-object#30]
I saw that this format is not recognized: `git://github.com/feross/standard.git`

Source: https://github.com/feross/standard/blob/55180064f1c55c869c978ac79f48a06c0e2f593e/package.json#L68

**Comment by zeke** [comment]
Are you sure? If not it's a regression.

![screen shot 2017-06-19 at 1 53 59 pm](https://user-images.githubusercontent.com/2289/27305519-c58d9e3e-54f6-11e7-86c2-936a2d76f03e.png)

https://zeke.github.io/github-url-to-object/

**Comment by bfred-it** [comment]
Sorry I forgot to add this: https://git.io/standard

**Comment by zeke** [comment]
So this is a git.io issue then, right?

**Comment by bfred-it** [comment]
Honestly I hadn't tested directly, I only found that the URL wasn't recognized when I imported this package in npmhub. But I tested it now and it does not work

**Comment by bfred-it** [comment]
Demo:

```sh
npm i  github-url-to-object
echo "console.log(require('github-url-to-object')('git://github.com/feross/standard.git'))" | browserify - | pbcopy
# then paste your clipboard into chrome's console
```

(Debugging this now)

**Comment by bfred-it** [comment]
Here's the issue, at least in the browser. I don't know what's up with git.io

<img width="850" alt="screen shot 2017-06-20 at 09 53 23" src="https://user-images.githubusercontent.com/1402241/27313038-661005f2-559e-11e7-8e64-f589ba2c4e2a.png">

```js
new URL('git://github.com/feross/standard.git')
> URL {
  hash: ""
  host: ""
  hostname: ""
  href: "git://github.com/feross/standard.git"
  origin: "git://"
  password: ""
  pathname: "//github.com/feross/standard.git"
  port: ""
  protocol: "git:"
  search: ""
  searchParams: 
  URLSearchParamsusername: ""
  __proto__: URL
}
```

**Comment by zeke** [comment]
Oh I see. I forgot that https://github.com/zeke/github-url-to-object/pull/28 happened and we stopped using node's URL parser in the browser.

I don't have a problem bringing back the `url` dependency if it solves this issue.

**Comment by bfred-it** [comment]
I may be wrong but, _how hard can it be to parse the `hostname` and `pathname`?_ Maybe we can just do that locally.
