### ISSUE TITLE
Git url reports a wrong branch

### ISSUE THREAD

**Issue by vladikoff** [zeke/github-url-to-object#9]
Given a git url: `git://github.com/vladikoff/fxa-content-experiments.git#mailcheck` the branch is not parsed correctly.

### Failing test case:

```
it('parses branch properly with a git:// url', function () {
  var obj = gh('git://github.com/vladikoff/fxa-content-experiments.git#mailcheck')
  console.log(obj)
  assert.equal(obj.branch, 'mailcheck')
})
```

### Result
```
{ user: 'vladikoff',
  repo: 'fxa-content-experiments',
  branch: 'master',
  tarball_url: 'https://api.github.com/repos/vladikoff/fxa-content-experiments/tarball/master',
  https_url: 'https://github.com/vladikoff/fxa-content-experiments',
  travis_url: 'https://travis-ci.org/vladikoff/fxa-content-experiments',
  api_url: 'https://api.github.com/repos/vladikoff/fxa-content-experiments' }
```
```
 AssertionError: "master" == "mailcheck"
```

**Comment by pdehaan** [comment]
I think the issue is at [/index.js:46](https://github.com/zeke/github-url-to-object/blob/a1e98982168a12b60a42dbb9f1032b75b6d9aa3f/index.js#L46)

Since you're already parsing the URL above on line 33, it may be enough just to check for a hash on the query string:
```js
obj.branch = parsedURL.hash && parsedURL.hash.replace(/^#/, '') || 'master'
```

**Comment by zeke** [comment]
@vladikoff is this still an issue?

**Comment by vladikoff** [comment]
@zeke Yes, the failing test case that I provided still fails on master for me

**Comment by zeke** [comment]
Ah I see. The `#branchname` style is only supported for shorthand repo names like `user/repo#branch` or `github:user/repo:branch` (the shorthand style used by npm3).

For fully-qualified URLs, the hashy branch syntax is not supported.

**Comment by vladikoff** [comment]
@zeke I think the confusion comes from the fact that npm supports that syntax. But oh well

**Comment by zeke** [comment]
Ah I didn't know that. I will accept a patch if you want to implement it.
